### ISSUE TITLE
Automatic game mode operation

### ISSUE THREAD

**Issue by AndresMHerrera** [AndresMHerrera/Seek-And-Destroy-Missile-System#13]
As a game client or operator I want a Automatic game mode operation because I want to enter the competition. During this mode the software should be able to aim at targets (given the coordinates of the target, or by target detection using video feed) and shoot enemy targets. 
specifically, when the operator begins the game the software should, 
* load selected game from the game server
* calibrate the missile launcher (could be done before starting game)
* be able aim at targets (reading target files or using target detection using video feed)
* shoot at targets (this will involve communication between the software and game server)
* be able to identify when no more targets left to hit
* end game
* prompt user for further actions

**Comment by AndresMHerrera** [comment]
should we also keep track of number of missed shots?

**Comment by AndresMHerrera** [comment]
We need to include a feature that stops the game when it reaches 60 seconds of game time.

**Comment by xcosmos6** [comment]
Yes, I think we can keep tracking of total missed shots.
As for tracking the 60 seconds game time and stop the game, we could do that if we found out we can never finish our game in 60s. However, if we do always finish game in 60s, we don't have to worry about that.

**Comment by AndresMHerrera** [comment]
We will stop the game when 60 sec limit reached or there are no targets left to hit. Automatic game mode only.

**Comment by AndresMHerrera** [comment]
ID: 107
Name: Automatic game mode operation
Pre-Condition: a game must be loaded, and to push start button. 
Normal Steps: 
* calibrate the missile launcher (could be done before starting game)
* be able aim at targets (reading target files or using target detection using video feed)
* shoot at targets (this will involve communication between the software and game server)
* be able to identify when no more targets left to hit
* end game
* prompt user for further actions
Alternative Steps: could select manual mode
Post-Condition: a game will be played after selecting automatic mode
