### ISSUE TITLE
CLI - loading games from server or directory of target files

### ISSUE THREAD

**Issue by AndresMHerrera** [AndresMHerrera/Seek-And-Destroy-Missile-System#15]
As a game client I want to be able to load games from a server or directory of target files, because each game consists of a list of targets. This is a especially important functionality in the early development of the software because, since target detection using video feed will not be implemented until later, we depend on the files for target locations. In short, this will allow to test the correctness of the calibration of the missile launcher.   
As an operator I want to be able to choose a game because I want to test a certain functionality of my application.   
1. ID: 013
2. Name: game client load game from server or directory of target files.
3. Pre-Condition: The operator is ready to start a game, and the game client is communicating with the game server.
4. Normal Steps: The operator type "loadgames" command in the CLI and the game client download list of games from the game server, then the operator will use the "load 'game number' " command to load one of the games.
5. Alternative Steps: N/A
6. Post-Condition: a game is loaded.

**Comment by xcosmos6** [comment]
we are loading game from a target file, not from the server, will close this one and create a new issue.
