### ISSUE TITLE
Creating a CLI

### ISSUE THREAD

**Issue by AndresMHerrera** [AndresMHerrera/Seek-And-Destroy-Missile-System#2]
As a operator I want a command line interface, because this will allow me to develop and test the application much more efficiently and easily, rather then working with a graphical user interface. The command line interface will be used for development and testing purposes, as mentioned, but it will also be possible to play a game using CLI.

for more detail view iteration 2 description under Wiki.

**Comment by AndresMHerrera** [comment]
ID: 111
Name: CLI
Pre-Condition: N/A
Normal Steps: launch the CLI application and enter commands for the software to execute. 
Alternative Steps: N/A
Post-Condition: command line interface should read user input.

**Comment by xcosmos6** [comment]
CLI is done. Able to process user input commands.
