### ISSUE TITLE
Live Video Streaming

### ISSUE THREAD

**Issue by AndresMHerrera** [AndresMHerrera/Seek-And-Destroy-Missile-System#3]
*video control*
As a game Client I want Live Video Streaming, because this will allow for detecting enemy targets.
As the operator, I want live video streaming because this allows me to see the game field via the camera and calibrate the missile turret.

This live video stream should be displayed inside the GUI or as a separate window when we use the CLI.

a, In the GUI, there should be a botton a "turn video on" button, when click, the video turns on and the same button now reads "turn video off". When click this "turn video off" button, the GUI should stop the live video stream and give a last snapshot of the video and leave it in the video window.

b, In the CLI, when we type "video on", the video window should pop up as a separate window. And when we type "video off", this video window should be retain the last snapshot of the scene and remain open till the operator manully close the window by click on the "X" to force thel window close.

1. ID: 005
2. Name: video stream
3. Pre-Condition: The operator submitted their team name and entered the main wireframe.
4. Normal Steps: click video on button to start the live video stream.
5. Alternative Steps: click video off button to stop the live video stream.
6. Post-Condition: the video stream is on in the main wireframe of the GUI.

**Comment by xcosmos6** [comment]
This live video stream should show in the GUI or as a separate window when we use the command line interface.

**Comment by AndresMHerrera** [comment]
As a gameClient I want Live Video Streaming, because this will allow for detecting enemy targets.

**Comment by AndresMHerrera** [comment]
Hi, I am not sure about this. I still have a lot of questions regarding the different features of the project. I will stay after class on tuesday to speak to the professor, and have all my questions answered.

**Comment by AndresMHerrera** [comment]
As a gameClient I want Live Video Streaming, because this will allow for detecting enemy targets.
