### ISSUE TITLE
read target files

### ISSUE THREAD

**Issue by AndresMHerrera** [AndresMHerrera/Seek-And-Destroy-Missile-System#9]
As a game client I want the software to read target files that contain the coordinates of the targets because, they are necessary so that the missile launcher can aim in the direction necessary to hit enemy targets. 

Furthermore, knowing the location of the targets is necessary because we have to consider the case where the target location is not in the playing field. If this does occur, then the software has to use target detection to identify the location of foe targets using the camera.

**Comment by AndresMHerrera** [comment]
ID: 109
Name: read target files
Pre-Condition: the software must connected to the server and must have target files to read
Normal Steps: Steps consist of, connecting to server and asking for the target files. When the target files are read, the software must store all the targets. 
Alternative Steps: If no target file supplied, then the software must obtain target coordinates by using target detection using the webcam. 
Post-Condition: software must have a list of targets to to begin a game.

**Comment by xcosmos6** [comment]
able to read ini target files and parse the file and store target information in a list
